-- Import Nifty 50 stocks from list_50.xlsx
-- Run this with: psql $DATABASE_URL -f scripts/import-nifty50-assets.sql

INSERT INTO assets (symbol, name, type, exchange, enabled) VALUES
('RELIANCE', 'Reliance Industries Ltd', 'indian_stock', 'NSE', true),
('HDFCBANK', 'HDFC Bank Ltd', 'indian_stock', 'NSE', true),
('ICICIBANK', 'ICICI Bank Ltd', 'indian_stock', 'NSE', true),
('SBIN', 'State Bank of India', 'indian_stock', 'NSE', true),
('BHARTIARTL', 'Bharti Airtel Ltd', 'indian_stock', 'NSE', true),
('INFY', 'Infosys Ltd', 'indian_stock', 'NSE', true),
('TCS', 'Tata Consultancy Services Ltd', 'indian_stock', 'NSE', true),
('HINDUNILVR', 'Hindustan Unilever Ltd', 'indian_stock', 'NSE', true),
('ITC', 'ITC Ltd', 'indian_stock', 'NSE', true),
('LT', 'Larsen & Toubro Ltd', 'indian_stock', 'NSE', true),
('KOTAKBANK', 'Kotak Mahindra Bank Ltd', 'indian_stock', 'NSE', true),
('AXISBANK', 'Axis Bank Ltd', 'indian_stock', 'NSE', true),
('BAJFINANCE', 'Bajaj Finance Ltd', 'indian_stock', 'NSE', true),
('ASIANPAINT', 'Asian Paints Ltd', 'indian_stock', 'NSE', true),
('MARUTI', 'Maruti Suzuki India Ltd', 'indian_stock', 'NSE', true),
('HCLTECH', 'HCL Technologies Ltd', 'indian_stock', 'NSE', true),
('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd', 'indian_stock', 'NSE', true),
('TITAN', 'Titan Company Ltd', 'indian_stock', 'NSE', true),
('ULTRACEMCO', 'UltraTech Cement Ltd', 'indian_stock', 'NSE', true),
('NESTLEIND', 'Nestle India Ltd', 'indian_stock', 'NSE', true),
('ONGC', 'Oil & Natural Gas Corporation Ltd', 'indian_stock', 'NSE', true),
('NTPC', 'NTPC Ltd', 'indian_stock', 'NSE', true),
('TATAMOTORS', 'Tata Motors Ltd', 'indian_stock', 'NSE', true),
('TATASTEEL', 'Tata Steel Ltd', 'indian_stock', 'NSE', true),
('POWERGRID', 'Power Grid Corporation of India Ltd', 'indian_stock', 'NSE', true),
('M&M', 'Mahindra & Mahindra Ltd', 'indian_stock', 'NSE', true),
('BAJAJFINSV', 'Bajaj Finserv Ltd', 'indian_stock', 'NSE', true),
('WIPRO', 'Wipro Ltd', 'indian_stock', 'NSE', true),
('TECHM', 'Tech Mahindra Ltd', 'indian_stock', 'NSE', true),
('ADANIENT', 'Adani Enterprises Ltd', 'indian_stock', 'NSE', true),
('ADANIPORTS', 'Adani Ports and Special Economic Zone Ltd', 'indian_stock', 'NSE', true),
('COALINDIA', 'Coal India Ltd', 'indian_stock', 'NSE', true),
('DIVISLAB', 'Divi''s Laboratories Ltd', 'indian_stock', 'NSE', true),
('DRREDDY', 'Dr. Reddy''s Laboratories Ltd', 'indian_stock', 'NSE', true),
('EICHERMOT', 'Eicher Motors Ltd', 'indian_stock', 'NSE', true),
('GRASIM', 'Grasim Industries Ltd', 'indian_stock', 'NSE', true),
('HEROMOTOCO', 'Hero MotoCorp Ltd', 'indian_stock', 'NSE', true),
('HINDALCO', 'Hindalco Industries Ltd', 'indian_stock', 'NSE', true),
('INDUSINDBK', 'IndusInd Bank Ltd', 'indian_stock', 'NSE', true),
('JSWSTEEL', 'JSW Steel Ltd', 'indian_stock', 'NSE', true),
('SBILIFE', 'SBI Life Insurance Company Ltd', 'indian_stock', 'NSE', true),
('TATACONSUM', 'Tata Consumer Products Ltd', 'indian_stock', 'NSE', true),
('CIPLA', 'Cipla Ltd', 'indian_stock', 'NSE', true),
('BPCL', 'Bharat Petroleum Corporation Ltd', 'indian_stock', 'NSE', true),
('BRITANNIA', 'Britannia Industries Ltd', 'indian_stock', 'NSE', true),
('APOLLOHOSP', 'Apollo Hospitals Enterprise Ltd', 'indian_stock', 'NSE', true),
('HDFCLIFE', 'HDFC Life Insurance Company Ltd', 'indian_stock', 'NSE', true),
('UPL', 'UPL Ltd', 'indian_stock', 'NSE', true),
('BAJAJ-AUTO', 'Bajaj Auto Ltd', 'indian_stock', 'NSE', true),
('LTIM', 'LTIMindtree Ltd', 'indian_stock', 'NSE', true)
ON CONFLICT (symbol) DO NOTHING;
